spring:
  application:
    name: artemyev-telegram-bot
server:
  port: 8081
bot:
  botName: ${BOT_NAME}
  token: ${BOT_TOKEN}
registration:
  url: http://localhost:8080/v2/users
account:
  create-url: http://localhost:8080/v2/users/{id}/accounts