name: base-ci
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: copy project
        uses: actions/checkout@v4
      - name: install JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Build project
        run: ./gradlew build -x test
      - name: Test project
        run: ./gradlew test
